// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npkpdwrhdtyfgvjherkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wa3Bkd3JoZHR5Zmd2amhlcmtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMTM3MDIsImV4cCI6MjA2OTU4OTcwMn0.B2ydITqLiBsJ-4jLVwDBeq4gbwFbf0Eb0G7LojFA7c8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});